package com.javaguru.student_vladimir_petranovski.lesson_13.level_6.rules_for_validation;

public enum Rules {

    RULE_1_NAME_NOT_EMPTY,
    RULE_2_NAME_ISNT_LESS_3_SYMBOLS,
    RULE_3_NAME_ISNT_BIGGER_100_SYMBOLS,
    RULE_4_NAME_MUST_CONTAIN_ONLY_ENGLISH_LETTERS_AND_NUMBERS,

    RULE_5_PRICE_MUSTNT_BE_EMPTY,
    RULE_6_PRICE_MUST_BE_BIGGER_ZERO,

    RULE_7_DESCRIPTION_MUSTNT_BE_DIGGER_2000_SYMBOLS,
    RULE_8_DESCRIPTION_MUST_CONTAIN_ONLY_ENGLISH_LETTERS_AND_NUMBERS
}
